---
url: "https://raw.githubusercontent.com/bedita/bedita/feature/v4/swagger-ui-bearer-authorization/plugins/BEdita/API/spec/be4.yaml"
dom_id: "#swagger-ui"
validatorUrl: "https://online.swagger.io/validator"
oauth2RedirectUrl: "http://localhost:3200/oauth2-redirect.html"
